### ISSUE TITLE
Import error when checking out and starting t3-start branch

### ISSUE THREAD

**Issue by atomboulian** [apollographql/graphql-tutorial#28]
Hi I tried starting on the 3rd tutorial today and I get this weird error:
```
[02:28:56] (~/tutorials/graphql-tutorial)
 (t2-start) $ rm -rf server
[02:29:12] (~/tutorials/graphql-tutorial)
 (t2-start) $ git checkout t3-start
D	server/.babelrc
Branch t3-start set up to track remote branch t3-start from origin.
Switched to a new branch 't3-start'
[02:31:29] (~)
 $ cd tutorials/graphql-tutorial/
[02:31:36] (~/tutorials/graphql-tutorial)
 (t3-start) $ cd server
[02:31:42] (~/tutorials/graphql-tutorial/server)
 (t3-start) $ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated graphql-server-core@0.6.0: critical bug related to GET queries fixed in v0.8.1

> fsevents@1.1.2 install /Users/anatomboulian/tutorials/graphql-tutorial/server/node_modules/fsevents
> node install

[fsevents] Success: "/Users/anatomboulian/tutorials/graphql-tutorial/server/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tutorial-server@1.0.0 No repository field.

added 460 packages in 8.889s
[02:31:55] (~/tutorials/graphql-tutorial/server)
 (t3-start) $ npm start

> tutorial-server@1.0.0 start /Users/anatomboulian/tutorials/graphql-tutorial/server
> nodemon ./server.js --exec babel-node -e js

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./server.js`
/Users/anatomboulian/tutorials/graphql-tutorial/server/server.js:2
import express from 'express';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at loader (/Users/anatomboulian/tutorials/graphql-tutorial/server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/anatomboulian/tutorials/graphql-tutorial/server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at Object.<anonymous> (/Users/anatomboulian/tutorials/graphql-tutorial/server/node_modules/babel-cli/lib/_babel-node.js:154:22)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by atomboulian** [comment]
Nevermid, did not mean to delete the .babelrc! all is well.
